### ISSUE TITLE
sort into package depending on table instead of type

### ISSUE THREAD

**Issue by BobHogvall** [ithsjavagroupd/project#20]
we now have controller etc as packages. I was thinking it might be better with one package for employee, chain etc.

**Comment by figgge** [comment]
I find it easier to navigate the packages using a controller package, entity package, etc. But I can budge if most of us think packages for each table are better.

**Comment by BobHogvall** [comment]
Then we can skip it! I just remembered Martin saying something about it when we did jakarta

**Comment by RehasLiamsi** [comment]
Closing the issue.
