### ISSUE TITLE
remove member from the ChainName repository

### ISSUE THREAD

**Issue by BobHogvall** [ithsjavagroupd/project#77]
The repository ChainName should only be used for projections. Do we want to show a list of members for every chain when we look at it through dto? I think that should be protected information. 

If we want to keep it it needs to be eager. So either remove it or make it eager.

**Comment by Lugn1** [comment]
I agree with the protected information. I did mention it in #73 . We could however list all names (or maybe a member count) since it's not really considered as sensitive information if I recall correctly.

**Comment by Svartkettil** [comment]
The count approach seems reasonable to me
